# This is a basic workflow to help you get started with Actions

name: Spring Build Pipeline
run-name: Spring Build Pipeline

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  # jobs run in parallel unless we use the needs key word
  build: #VM
    runs-on: ubuntu-latest

    steps: 
          # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: AWS login
        uses: aws-actions/configure-aws-credentials@v4
        with:
           # AWS Access Key ID. Provide this key if you want to assume a role using access keys rather than a web identity token.
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          # AWS Secret Access Key. Required if aws-access-key-id is provided.
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: JDK installation
        uses: actions/setup-java@1
        # actions/setup-java@v3.12.0
        with:
            distribution: "" # changes depending on the java version we're using
            java-version: "8"

      - name: Build project in maven
        run: mvn -b package --file https://github.com/tamara-703/cabinResort-backend/blob/main/pom.xml

      - name: list files
        run: ls -la spring/githubprojectname/target

      - name: deploy
        working-directory: {githubpom.xmllinkfor project}
        run: aws s3 cp * s3:://anything/
      
          

  # post-build: #VM2
  #   needs: build
  #   runs-on: ubuntu-latest
